### ISSUE TITLE
Add HTML data option [enhancement]

### ISSUE THREAD

**Issue by sanderjson** [open-source-labs/Svelvet#112]
I would love to be able to render my own HTML within custom nodes.

```
data: {
		label: "<p>my cool HTML string</p>"
                label_type: "HTML"
	}
```

<img width="368" alt="image" src="https://user-images.githubusercontent.com/20689537/186390342-35a4473f-38e6-4b03-b442-397f1d09f9da.png">

**Comment by sanderjson** [comment]
Yes, this is great. Breaking change for 4.0?

**Comment by rchrdnsh** [comment]
Both html and svelte elements/components would make this infinitely more useful and awesome. I second this idea :-)

**Comment by ronvoluted** [comment]
If you're happy to use a hack until maintainers add it, you can modify `node_modules` to get this working. Add the following two lines at `/node_modules/svelvet/Containers/GraphView/index.svelte#L75`:

```diff
      {#if node.image && !node.data.label}
        <ImageNode {node} {key} />
+     {:else if node.data.html}
+       <Node {node} {key}>{@html node.data.html}</Node>
      {:else}
        <Node {node} {key}>{node.data.label}</Node>
```

Then use a `html` property instead of the usual `label`:
```ts
const nodes = [
  {
    id: 1,
    width: 100,
    height: 100,
    position: { x: 0, y: 250 },
    data: { html: `<p>This is <a href="https://html.com">HTML</a></p>` },
  },
];
```

Go wild!:
<img width="596" alt="Screenshot 2022-10-12 at 7 56 57 pm" src="https://user-images.githubusercontent.com/5785323/195315138-e8675cca-2a28-4306-b097-23631a793ff9.png">
