### ISSUE TITLE
Can not run a local version [bug]

### ISSUE THREAD

**Issue by sanderjson** [open-source-labs/Svelvet#113]
Steps to reproduce: create a new fork, npm i, npm run dev, localhost:3000

```
Error: supabaseUrl is required.|
```

Might be related to v2.02 features:

+ Added a REPL to our documentation site
+ Added SQL database to our REPL
+ Added GitHub OAuth to enable users to save their custom diagrams created in our new REPL

**Comment by sameev** [comment]
Hi @sanderjson - I believe you're not able to run a local version because forked repos are missing the .env file which contains the Supabase URL & Anon Key. In order to run a local version you will need to perform the following steps:

1. Create an account on [Supabase](https://supabase.com/)
2. Create a new project in Supabase (you can name this whatever you want)
3. Add a ".env" file to your forked repo with the following (see screenshot for what this looks like in Supabase):
`VITE_SVELTE_APP_SUPABASE_URL="[INSERT NEW PROJECT API KEY]"
VITE_SVELTE_APP_SUPABASE_ANON_KEY="[INSERT NEW PROJECT SECRET]"`

Once that is done you should be able to render the website locally on localhost:3000, although you will be missing some minor functionality tied to the production database (incl. OAuth login).

![Screen Shot 2022-09-01 at 4 25 45 PM](https://user-images.githubusercontent.com/103392009/188030192-55410ffc-9a93-40dd-a45e-0d9fc7550b09.png)
