### ISSUE TITLE
movement={false} should not set css attribute cursor: move;

### ISSUE THREAD

**Issue by pappasam** [open-source-labs/Svelvet#152]
Version: Svelvet 4.0.3

When `svelvet` is initialized with `movement={false}`, nodes still have the attribute `cursor: move;` set. This should not be set on nodes when movement is false. On the latest version of Firefox, this causes the cursor to look like a gloved hand, which indicates that a component can be dragged, which is obviously not the desired behavior in this case.

```svelte
<Svelvet
  nodes={initialNodes}
  edges={initialEdges}
  bgColor="transparent"
  background={false}
  movement={false}
/>
```

![image](https://user-images.githubusercontent.com/3723671/202967978-2dd12637-1715-466e-9a17-09db4c5cfabc.png)

**Comment by ErnestoGonza** [comment]
Hi @pappasam, sorry for the delayed response we actually just took on a massive endevour to refactor the entire store for Svelvet 6.0 and we actually took care of addressing this issue while we were at it. The cursor should only change when you are able to move the nodes now. P.S. the name is now locked instead of movement. Thank you for the feedback, we are always looking to see how we can improve svelvet!
