### ISSUE TITLE
Feature: Multiple connectors on same side

### ISSUE THREAD

**Issue by Rimevel** [open-source-labs/Svelvet#155]
It does not currently seem possible to have multiple connection points on a side. Would love to see this as a feature as it would open up a lot of cool use-cases. Picture for demonstration:
![image](https://user-images.githubusercontent.com/4656465/208502017-fb823761-9496-4867-b393-45c62f5c3829.png)

**Comment by jerzakm** [comment]
This would be awesome. I was looking for a svelte library that could do this for my current project.

**Comment by zacharygriffee** [comment]
+1 to this feature. I'm actually looking to develop something similar to the unreal blueprints as well. I called my use-case particular in my feature request post here https://github.com/open-source-labs/Svelvet/issues/175#issue-1529658238 but, the unreal blueprints; is at essence the use-case I'm speaking of, with some modifications.

**Comment by rachelheplus** [comment]
Hi @Rimevel , @jerzakm , and  @zacharygriffee ,

We are soft launching Svelvet 6.0 and there's a new feature that developers can pass in anchor position callback functions to customize the number and the places of anchors on a single node. The gif attached at the bottom visualizes a node with 3 customized anchors on its left side. And here is a StackBlitz link for how to implement this new feature: https://stackblitz.com/edit/sveltejs-kit-template-default-w7fvtb?file=src/routes/+page.svelte  

Below is an example of custom anchor position callback. 

```
const topAnchor = (xNode, yNode, widthNode, heightNode) => {
  const xAnchor = xNode;
  const yAnchor = yNode + heightNode / 6;
  return [xAnchor, yAnchor, 180];
 };
```

![feature_custom_anchors](https://user-images.githubusercontent.com/30616327/217657441-cac58332-3a16-45de-9a6e-3f2096b37668.gif)

**Comment by NumberPigeon** [comment]
hi @rachelheplus thanks for your work and explanation! 

I read the example code, and found it seems multi anchors can only be implemented by callbacks, which seems only work when edges are rendering. I wonder if it's possible to render a node with multiple anchors on the same side **without** any edges, so it would be good to build many interactive apps.

**Comment by michael-chiang-dev5** [comment]
Hi @NumberPigeon 

Can you explain what you mean by multiple anchors on the side without any edges? Do you mean the interactive anchors in this example (https://www.svelvet.io/docs/Interactive-Nodes/), except that the anchors are placed arbitrarily instead of the 4 sides?

If so, it is possible. We set the position of the interactive anchors the same way we set the position of edge anchors, so as long as there is a good way for the user to pass in that information it should be straightforward to place interactive anchors. Right now, there may be some new developers coming into work on Svelvet so we are focusing on stability and documentation for the meantime, but reopening this ticket as this seems like a good feature to add in.

**Comment by NumberPigeon** [comment]
> Hi @NumberPigeon
> 
> Can you explain what you mean by multiple anchors on the side without any edges? Do you mean the interactive anchors in this example (https://www.svelvet.io/docs/Interactive-Nodes/), except that the anchors are placed arbitrarily instead of the 4 sides?
> 
> If so, it is possible. We set the position of the interactive anchors the same way we set the position of edge anchors, so as long as there is a good way for the user to pass in a callback defining the interactive anchor position it should be straightforward to place interactive anchors. Right now, there may be some new developers coming into work on Svelvet so we are focusing on stability and documentation for the meantime, but reopening this ticket as this seems like a good feature to add in.

Hi michael, ya I do mean the interactive anchors on the same side. I wonder is there is a method to implement it currently? 

Besides, I found when I connect, say the anchor 1 of Node A to the anchor 2 of Node B, it will connect the Node A and B without caring about which anchor I choose, but connect the nearest ones. I guess it's because Svelvet's edge only focus on which **nodes** are the source and the target, but not the **anchors**. I think it would also be a good feature if Svelvet can keep the same anchors the user chose to connect.

**Comment by briangregoryholmes** [comment]
This feature is now fully implemented in Svelvet 7. Thank you for your contribution!
