### ISSUE TITLE
BUG - dynamic render

### ISSUE THREAD

**Issue by bogdankol** [open-source-labs/Svelvet#179]
Hi! I'm not sure if that's me or not, but when I tried to render another nodes by pressing button - new nodes didn't appear (yet in console it changed). And also when I updated Svelvet version to 5.0.7 from 4.0.3 - nodes stuctured as {data: {html: htmlString}} didn't seem to work either (dynamic change), but if I install version 4.0.3 - htmlStrings are working and dynamic render too

But if I change node content in .svelte component (not passing new array of nodes into Svelvet) - it works

**Comment by msze400** [comment]
I commented on this issue (https://github.com/open-source-labs/Svelvet/issues/181) as well but as my team is having similar issues transitioning to Svelvet v5.0.7 because of this dynamic rendering issue

**Comment by ErnestoGonza** [comment]
Hello, I believe this issue was addressed in 5.0.8 but if it was not already addressed we actually just got done doing a soft launch for Svelvet 6.0. I have a stackblitz link with an example of the updated version, you can go to the bottom and have the option to click the button below to add a new node and watch it render dynamically. I hope this helps, if there are any other issues our team is always trying to work on Svelvet and improve it. https://stackblitz.com/edit/sveltejs-kit-template-default-39mwlk?file=src/routes/+layout.svelte
