### ISSUE TITLE
We can't find a way to dynamically change the Svelvet Diagram in version 5

### ISSUE THREAD

**Issue by Andrii-Moshenskyi** [open-source-labs/Svelvet#181]
Previously, changing the initialNodes array changed the displayed nodes. Right now, any changes to initialNodes after the chart array has been rendered have no effect. What to do?

In addition, is it possible, using some kind of callback function, to get data on how exactly the user manipulated the rendered diagram in order to save this data in the backend?

**Comment by msze400** [comment]
Likewise. Previous in Svelvet v4 we had the ability to dynamically change the edges and add additional nodes. This is now bugged as it seems transitioning to version 5 killed the reactivity of our Svelvet canvas container. 

Since our nodes get initialized after the canvas is mounted because we have to load them from the database (frontend terminology probably incorrect here), our networks don't show up on the canvas

**Comment by dmckenna44** [comment]
Thanks for catching that! This issue should be fixed as of v5.0.8

**Comment by ErnestoGonza** [comment]
Hello, I believe this issue was addressed in 5.0.8 but if it was not already addressed we actually just got done doing a soft launch for Svelvet 6.0. I have a stackblitz link with an example of the updated version, you can go to the bottom and have the option to click the button below to add a new node and watch it render dynamically. I hope this helps, if there are any other issues our team is always trying to work on Svelvet and improve it. https://stackblitz.com/edit/sveltejs-kit-template-default-39mwlk?file=src/routes/+layout.svelte
