### ISSUE TITLE
Scope mouse events

### ISSUE THREAD

**Issue by jakegibson** [open-source-labs/Svelvet#239]
Event listeners need to be scoped to svelvet created dom elements. Basic repro below of how it clobbers a basic drag and drop example.
Fairly new to svelte but going to guess `svelte:window` is generally going to be less than ideal. I'll dig into it a little more tomorrow but would be happy to hear I overlooked an existing setting for properly scoping.

 
Repro: https://svelte.dev/repl/ac4365c619eb46d9b9435d0a708591f6 (comment out the component to see it working or look at https://svelte.dev/repl/adf5a97b91164c239cc1e6d0c76c2abe?version=3.14.1)
If you inspect the non-svelvet elements and look at the eventlisteners you can see PotentialAnchors.svelte, Node, ResizeNode all adding listeners.

Related to https://github.com/open-source-labs/Svelvet/commit/20df1392f9aea38741f1d37d2513a1723dbb71ab

Background: Was trying to drag a dom element from outside of Svelte and create a svelvet node on drop.  Wiring up the functionality should be pretty straightforward as long as I can drag elements in and get the drop event.

**Comment by michael-chiang-dev5** [comment]
Hi @jakegibson,

Thank you for your detailed comment! Yes, 100% agree that `svelte:window` in node components is clumsy. When the initial logic involving mouse events was written, my guess is that there was a desire to keep logic of dragging/clicking nodes all within the node component and `svelte:window` was used as a workaround to handle mouse events outside of the node rather than lifting state up to the canvas.

Right now, there is no option for proper scoping. One band-aid fix is to attach the mouse event listeners to the svelvet canvas instead of the entire document window. Would this solve your use case, or would mouse listeners on the svelvet canvas still break your functionality?

Thanks for your interest in Svelvet!

**Comment by jakegibson** [comment]
Sorry just getting back to this. Looks like my repro example is pretty view port sensitive. On my larger monitor you see a svevlet example and the example from the second repl link. Issue resolution would allow interacting with the non-svelvet drag and drop example with svelvet loaded on the same page. 

I'll try get time to put up a PR either scoping the svelte:window calls or bypassing the listening function if not a svelvet element, but no promises :) 

End goal for my specific use case is dropping a non-svelvet div on to the svelvet canvas, then on the drop event taking metadata associated with the dropped dive to create a new svelvet node

**Comment by jakegibson** [comment]
Example of desired functionality
https://reactflow.dev/docs/examples/interaction/drag-and-drop/

**Comment by jakegibson** [comment]
Just noticed it is not an issue in Firefox, just chrome varieties

**Comment by michael-chiang-dev5** [comment]
Hi @jakegibson 

Thanks for the PR! Will take a look later this week. Did this PR fix your use case? 

I have not tested yet, but my initial thought was that any issues with dragging elements from an outside div into the Svelvet canvas would be with Event.preventDefault(), and the scoping event listeners to the canvas would not solve the issue because the div is still being dragged onto the canvas. Just wondering if this solves things or whether there are more changes needed.

**Comment by jakegibson** [comment]
Yes it did fix my use case. I think because it allowed the drag event flow to start. I do think the preventDefault() would be better off dropped if there isn't a case that is solving for, but wanted to keep my changes as minimal as possible

**Comment by briangregoryholmes** [comment]
Our goal with Svelvet 7 is to have only two svelte:window scoped mouse events created by the top most component for mouse up and mouse move. These sync with the store, which allows any other component to subscribe to this information when necessary. Every other mouse event is scoped to the component.
