### ISSUE TITLE
Zoom is super sensitive in latest version

### ISSUE THREAD

**Issue by eliasdefaria** [open-source-labs/Svelvet#291]
Hi there - love Svelvet, but the latest version (7) seems to make my canvas super sensitive to zooming. I'm curious if you all increased the sensitivity or if this is a configurable parameter on the `<Svelvet>` element. I wasn't able to find anything in the docs for this other than the `increment` property on the controls but this seems to only work on the actual control buttons.

Just checked out the latest example you all have on your website and it seems the zoom issues are present there as well. This makes things quite tough from a UX standpoint :( 

Note: This was tested on two chromium-based browsers on Mac M1 and M2.

**Comment by briangregoryholmes** [comment]
The wheel events fired on Mac trackpads are higher resolution than other input devices. There's supposed to be a debounce on scroll events to normalize this and I'm not seeing it in the latest version. This will be fixed tonight.

**Comment by eliasdefaria** [comment]
Awesome! Thanks for the quick response :)

**Comment by briangregoryholmes** [comment]
@eliasdefaria Fix is live now. Let me know how it feels and I can make adjustments.

Added a few related features while working on this.

If you hold down the shift key while scrolling (regardless of input type), you'll get a slower, more "precise" zoom.

If you hold down the meta key (CMD on Mac), you'll enable two finger pan (with pinch to zoom) similar to the native Maps app. You can leave this on by default by passing the trackpadPan prop to Svelvet, but I'm not adding it to the docs for now because the implementation interferes with non-trackpad scroll behavior. Will look for a better way to differentiate between the two types of wheel events.

Thanks for bringing this to our attention.

**Comment by eliasdefaria** [comment]
Wow - such a quick fix! Works much better now. Total UX lifesaver. Thanks so much!
