### ISSUE TITLE
Anchor `invisible` breaking with tailwind

### ISSUE THREAD

**Issue by rohanrajpal** [open-source-labs/Svelvet#313]
The following stackblitz by @briangregoryholmes is working as expected.

https://stackblitz.com/edit/vitejs-vite-zd3zfq?file=src/App.svelte

But if I add tailwind to the project, dropping the edge on node is no longer working

https://stackblitz.com/edit/vitejs-vite-oorx1h?file=src/App.svelte

Here's the repo to repro locally https://github.com/rohanrajpal/invisible-edge-repro

**Comment by briangregoryholmes** [comment]
I've changed the implementation of this idea in the latest version and it should no longer conflict with Tailwind.

The relevant prop on the Anchor is now called `nodeConnect` rather than `invisible`. It works regardless of where the Anchor is placed. If you set `nodeConnect` on multiple Anchors, we'll just assign connections to them in order.

The `invisible` prop now just doesn't render out the default Anchor, which is useful in certain cases.

**Comment by rohanrajpal** [comment]
Works just as expected & solves my issue with #314 too, thanks a ton!
