### ISSUE TITLE
two way binding to nodes

### ISSUE THREAD

**Issue by madhudson** [open-source-labs/Svelvet#331]
I can't seem to find an event or binding to allow me to update after a node is moved. I see that you updated the Node API to allow connection and disconnection events though

**Comment by briangregoryholmes** [comment]
Yeah, we don't bind back to the position object mostly because we think the DX around that isn't great. But we're actively looking into ways to make it seamless.

That said, I can easily add events that are triggered internally. Something like `on:nodeMoving` would fire on every positional change and would send along the current position. I can experiment with enabling this over the weekend and let you know when it's released.

**Comment by madhudson** [comment]
that's great thanks. I modified some of the code base in v4.x and added a dispatcher to where the store was being modified with certain changes and exposed the event, which worked great, but thought I'd try to use the newer API

**Comment by briangregoryholmes** [comment]
Hey, Mad. While we work on the implementation, I added a readonly binding to the position prop on Nodes in v7.0.47. See below.

```html
<script lang="ts">
	import { Svelvet, Node } from 'svelvet';
	let position = { x: 300, y: 300 };
</script>

<body>
	<Svelvet >
		<Node bind:position />
	</Svelvet>
</body>
```

**Comment by madhudson** [comment]
thank you!
