### ISSUE TITLE
Broken code snippets on the website, lack of example code

### ISSUE THREAD

**Issue by crcdng** [open-source-labs/Svelvet#350]
* https://svelvet.mintlify.app/data-flow/overview 
* https://svelvet.mintlify.app/components/node (right side)
* https://svelvet.mintlify.app/components/anchor

all throw errors due to different reasons. Can you test / check / update  the snippets and/or provide a comprehensive, working example?

**Comment by briangregoryholmes** [comment]
These code snippets are provided as simplified examples and don't include things like class stylings (the snippets would be significantly larger). We should probably be more explicit about that. We are working on adding custom sandboxes for all the major components. For a comprehensive, working example that touches on all of these concepts, see the sandbox here: https://svelvet.mintlify.app/introduction

That said, I've reviewed the linked documentation and made the following changes:

/data-flow/overview

* The function is `generateInput` not `generateInputs`
* Added in line width and height props so that the Node has dimensions if you copy the snippet directly
/data-flow/overview

/components/node

* I did not see a functional issue with the right hand snippet, but added lang="ts" to the script tag since the function in the example does have a CustomEvent type annotation
* The import in the the main snippet should be `import MyNode ...` not `import { My Node } ...`
* I updated the heading of the center snippet to reflect that this code should be used on, for instance, a page route

/components/anchor

* Added an in-line comment emphasizing that the CustomAnchor is generic component that you can create and import
* There were no type annotations in this file, but I added the lang="ts" attribute to the script tag and imported the Connections type in case people are copying this into Svelte project using TypeScript
* Removed the edge prop just for clarity

Thanks!

**Comment by crcdng** [comment]
In the case of the two node snippets, if I put these together, the `nodeClicked` event does not work for me. `handleClick` is not called.

```
<script lang="ts">
  import { Node, Svelvet } from 'svelvet';

function handleClick(e: CustomEvent) {
  const { detail } = e;
  detail.node.set.bgColor('red');
}

</script>



<Svelvet>
	<Node id="55" let:grabHandle let:selected on:nodeClicked="{handleClick}">
    <div use:grabHandle class:selected class="my-component">
      <span>Click Me</span>
    </div>
  </Node>
	<Node id="alpha" bgColor="red" label="Default Node" />
</Svelvet>
```

**Comment by crcdng** [comment]
It would be useful if there would be a small step by step tutorial showing the main features or a small but more comprehensive example between step 1 and step 2 here:

<img width="729" alt="Screenshot 2023-05-11 at 20 09 44" src="https://github.com/open-source-labs/Svelvet/assets/830492/9774448e-bca3-4827-8b0c-0c84e07d6473">

**Comment by briangregoryholmes** [comment]
I totally agree.

Looks like nodeClicked not firing is an internal issue. The snippet should work. I'll try to get that fix and correlated test pushed as soon as possible.
