### ISSUE TITLE
Anchor positions do not update after panning, edges are disjoint from nodes

### ISSUE THREAD

**Issue by rungdung** [open-source-labs/Svelvet#402]
![image](https://github.com/open-source-labs/Svelvet/assets/71073145/0781e3c6-4433-45c3-8d26-a9ed053ab182)

Once I connect the anchors and pan around, the edges do not update and are stuck in the same window position, while the Svelvet canvas moves. 

Browsers: Firefox and Chrome
Svelvet version: 8.0.2

**Comment by briangregoryholmes** [comment]
I'm not able to reproduce this issue locally at the moment. Would you be able to put together a StackBlitz?

**Comment by Defferrard** [comment]
Hello, tt seems like it happens when you're defining height on the main component while its parent has height/width restrictions.

Here are the code that I used to reproduce :
```svelte
<script lang="ts">
  import svelteLogo from './assets/svelte.svg'
  import viteLogo from '/vite.svg'
  import Counter from './lib/Counter.svelte'
  import { Node, Svelvet } from "svelvet";
</script>

<main style="width:1000px; height:100px;">
  <Svelvet height={500}>
            <Node/>
            <Node/>
            <Node/>
          </Svelvet>
</main>
```

I've did a StackBlitz as asked : https://stackblitz.com/edit/vitejs-vite-6fsziq?file=src%2FApp.svelte (Never done that before, sorry if it isn't what you where wainting for)

I've tried on Microsoft Edge and got the same result.

**Comment by briangregoryholmes** [comment]
This was related to how we were recalculating Anchor positions and should likely only occur when the page has been scrolled vertically or horizontally. I've attempted to fix it with this https://github.com/open-source-labs/Svelvet/pull/422, but will need to do some more testing and will likely end up re-writing some of the functionality behind the scenes.
