### ISSUE TITLE
Minimap locking up Svelvet canvas

### ISSUE THREAD

**Issue by zkilleb** [open-source-labs/Svelvet#408]
While working with a branch on a new machine, I began to run into an issue where the Svelvet canvas no longer responded to any of my drag or click actions. Looking in the console, I see the error 

![Screenshot 2023-06-22 112317](https://github.com/open-source-labs/Svelvet/assets/14062781/a34a5abc-2791-4d94-9a32-16c823ba6687)

If I remove the minimap prop from the Svelvet component it starts to work again. I have deleted both my package-lock.json and node_modules directory and, after completing a fresh install, I am still running into this issue. I didn't see this issue on my other machine and my other teammates aren't currently seeing it either. 

Svelvet Version: 8.0.2
Browsers: Chrome, Edge

**Comment by briangregoryholmes** [comment]
Are you able to share a StackBlitz or some more detailed code to reproduce this?

This is happening in the MiniNode component, where we query the DOM to get the background color of the corresponding Node. The error message is essentially saying that the selector being used is not valid because it is being passed an ID that includes a JS object value rather than a string/number. I can recreate this error message by doing exactly that.

Assuming there isn't an underlying issue, my first step would be to ensure the ID of the Node is being set with a correct value. If you're using TypeScript, this would be caught by a linting error as only strings/numbers are accepted types for that prop. If we can eliminate that as a possibility, I can look around for what else might be causing it.
