### ISSUE TITLE
Unable to change node positions programmatically

### ISSUE THREAD

**Issue by kirbykatie** [open-source-labs/Svelvet#409]
Running into an issue when the ID of a node doesn't change, but the position does, the node is not re-rendered.
We are building an application that displays a variety of nodes and users can add filters to narrow what nodes are displayed. When that filtering occurs, we're running a function to re-calculate where the nodes should be positioned. However, the nodes themselves aren't getting re-rendered, so no repositioning occurs.

We've tested making the key in the for loop to be `node.position` instead of `node.id` but that led to a bug similar to [this issue](https://github.com/open-source-labs/Svelvet/issues/402).

Code:
```
<Svelvet width={innerWidth} height={innerHeight - 155} minimap controls>
		{#each initialNodes as node (node.id)}
			<PersonNode
				id={node.id}
				position={node.position}
				dimensions={node.dimensions}
				person={node.person}
				connections={node.connections}
				on:onNodeClicked={displayPerson}
			/>
		{/each}
	</Svelvet>
```

Svelvet canvas before filtering:
![Screen Shot 2023-06-22 at 11 31 47 AM](https://github.com/open-source-labs/Svelvet/assets/41655241/78d38bb2-fab1-42e6-845a-a9d3b6f8599a)

Canvas after positions are re-calculated (no nodes move position):
![Screen Shot 2023-06-22 at 11 31 59 AM](https://github.com/open-source-labs/Svelvet/assets/41655241/635b8fde-be50-4f2a-90ac-fee7b3541437)

Expected behavior:
![Screen Shot 2023-06-22 at 11 32 35 AM](https://github.com/open-source-labs/Svelvet/assets/41655241/20966eb7-d1e3-49bb-ba05-03bbc44689e2)

**Comment by briangregoryholmes** [comment]
So, prior to about five minutes ago, this was simply not a feature of the library. The position prop featured a read only binding plus the ability to set the initial position of the Node, but any subsequent changes were essentially ignored. Updating it programmatically required a different approach, for reasons that are probably not worth getting into.

That said, I've decided to enable the two-way data binding with a slightly less optimized workaround because I think developers, like yourself, expect this behavior.

Here's how it works:

```
<script lang="ts">
	import { Svelvet, Node } from '$lib';

	let position = { x: 300, y: 300 };

	$: console.log(position);

	function moveNode() {
		position = { x: 100, y: 100 };
	}
</script>

<Svelvet>
	<Node bind:position>
		<div>
			<p>{JSON.stringify(position)}</p>
			<button on:click={moveNode}>Move</button>
		</div>
	</Node>
</Svelvet>
```

Like normal Svelte reactivity, you have to make sure the position variable is explicitly on the left side of the assignment. Even if the Node is moved using the normal drag behavior, the local position variable will still update and the new position will be logged.

This is available in version 8.0.4. Please let me know if you have any issues implementing this or expect different behavior.

**Comment by kirbykatie** [comment]
Thank you!! I will update to 8.0.4 now and check it out.

**Comment by kirbykatie** [comment]
Working as expected. Thank you for the quick response on this!!
