### ISSUE TITLE
drag distance is biased by zoom level

### ISSUE THREAD

**Issue by laszlokorte** [open-source-labs/Svelvet#64]
I saw your announcement on hackernews. 

While playing around on your landing page I noticed that when dragging nodes, depending on the zoom level, the dragged node moves faster (when zoomed in) or slower (when zoomed out) than the cursor.

**Comment by anulepau** [comment]
hi thank you so much for your observation and raising this to us! we definitely see that too, and we'll do some more research and experimentation with d3-zoom to fix this issue, so stay tuned. i will comment again when we've released an update with the fix. in the meantime, if you feel called to contribute please feel free!

**Comment by Thomasorus** [comment]
Hi folks, any news on this?

I noticed the lack of zoom compensation during movement creates another bug. Since each node is managing its own movement using `on:mousedown` and `on:mouseup`, if you release your mouse click while your cursor is outside of the node due to distance, the `on:mouseup` is not triggered, resulting in nodes continuing to follow the cursor.

**Comment by TensionCoding** [comment]
This bug has been resolved as of [PR 100](https://github.com/open-source-labs/Svelvet/pull/100).
