### ISSUE TITLE
Not an issue : Edit on double click

### ISSUE THREAD

**Issue by orefalo** [open-source-labs/Svelvet#86]
Hi, far from an expert in this area - I just discovered d3 and your library.
First and foremost, it looks neat, and the code seems super simple/clean.

A simple newbie question: what would it take to enable "Edit node name on double click" ?

Ty

**Comment by emmanotly** [comment]
Hi @orefalo !

I am apart of the Svelvet 5.0 team! I really love this suggestion, and it is something the team and I have been discussing and would love to implement; we agree that this would be an incredible feature and would give Svelvet's users so many options for easy customization. We would like to implement this feature, and expand on it!

Given the current code base from previous Svelvet teams, there are some restrictions on ways we can accomplish this, but we are still actively trying to secure a viable solution that doesn't hinder the UX.

Svelvet 5.0's main priority is to address the issues and requests from the users to improve UX and UI.

Though I can't answer whether or not we will be able to address/complete this feature with our current time and other restrictions, I just wanted you to know that it is something we are actively discussing and working on getting a solid plan for.

I hope I can update you soon with some good news on this specific request!

Otherwise, we have already implemented some features that'll at least give the users more customizable options than the current version of Svelvet. Svelvet 5.0 will launch early January, and we look forward to your continued feedback.

Cheers!

**Comment by taylien96** [comment]
This now now possible however it is on right click in svelvet 5.0, thank you for your patience
